### ISSUE TITLE
Write directly to googlesheets

### ISSUE THREAD

**Issue by cansavvy** [jhudsl/cow#1]
Right now I just uploaded the file manually. Before I will be able to write directly, I will need to ensure that the data and notes aren't being overwritten or put out of order. (Not sure exactly how to accomplish this yet).

**Comment by avahoffman** [comment]
Are there any big advantages to having a google sheets output versus some kind of Rmd table that stays in github or an app? I guess I'm wondering whether we want more advanced capability (e.g., sorting, filtering).

**Comment by cansavvy** [comment]
We can definitely save it elsewhere, but we also want a place that authors will easily be able to add their corresponding likert questions and edit things if needed. Googlesheets are easy for people to navigate so that's kind of the motivation there. 

However, I'm open to brainstorming what might work better. We just need something that: 
1) Is stored online 
2) Authors can be given write access to. 

But we also might want something a bit more tightly controlled than a googlesheets? Like maybe we should have someone have to file a pull request in order to add to this sheet.
